# Generated by Django 4.1.2 on 2022-11-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
